
all: Ejemplo1 Ejemplo2 Ejemplo3 Ejemplo4

clean:
	rm -f Ejemplo1 Ejemplo2 Ejemplo3 Ejemplo4

Ejemplo1: Ejemplo1.c
	gcc -o Ejemplo1 Ejemplo1.c -Wall

Ejemplo2: Ejemplo2.c
	gcc -o Ejemplo2 Ejemplo2.c -Wall

Ejemplo3: Ejemplo3.c
	gcc -o Ejemplo3 Ejemplo3.c -Wall

Ejemplo4: Ejemplo4.c
	gcc -o Ejemplo4 Ejemplo4.c -Wall

